{% set name = "nep29" %}
{% set version = "0.0.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nep29-{{ version }}.tar.gz
  sha256: 4a4a23c963199895d4d94211bae8c9e64b28e4fa243dfbddc7f23cdd88f541d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nep29 = nep29.nep29:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - prettytable
    - requests
    - packaging

test:
  imports:
    - nep29
  commands:
    - pip check
    - pytest --pyargs nep29
  requires:
    - pip
    - pytest

about:
  home: https://github.com/hmaarrfk/nep29
  summary: NEP29 Calculator tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
